export const mockProducts = [
  {
    id: '1',
    title: 'Apple MacBook Air M2 13寸',
    price: 5800,
    originalPrice: 8499,
    image: 'https://ts4.tc.mm.bing.net/th/id/OIP-C.XIViuNxLvOR0Gf1AgFjv4gAAAA?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: '数码电子',
    condition: 'like-new' as const,
    description: '2023年购买，使用一年，电池健康度95%，无磕碰划痕，配件齐全。',
    sellerId: '2',
    sellerName: '李同学',
    sellerAvatar: '',
    campus: '狮子山校区',
    publishTime: '2小时前',
    views: 128,
    likes: 24,
    isLiked: false,
    isSold: false,
  },
  {
    id: '2',
    title: 'iPhone 14 Pro 256G 深空黑',
    price: 4200,
    originalPrice: 7999,
    image: 'https://qny.smzdm.com/202209/08/63195899e5b559982.jpg_e600.jpg',
    category: '数码电子',
    condition: 'good' as const,
    description: '使用一年半，屏幕有轻微划痕，功能正常，电池健康度88%。',
    sellerId: '3',
    sellerName: '王同学',
    sellerAvatar: '',
    campus: '成龙校区',
    publishTime: '5小时前',
    views: 256,
    likes: 45,
    isLiked: false,
    isSold: false,
  },
  {
    id: '3',
    title: '小米电动滑板车 Pro2',
    price: 1200,
    originalPrice: 2999,
    image: 'https://imgservice.suning.cn/uimg1/b2c/image/bAEoU6D65cVk40jVlDWR7w.jpg',
    category: '运动户外',
    condition: 'good' as const,
    description: '毕业出，使用两年，续航约30公里，轮胎有磨损，功能正常。',
    sellerId: '4',
    sellerName: '张同学',
    sellerAvatar: '',
    campus: '成龙校区',
    publishTime: '1天前',
    views: 89,
    likes: 18,
    isLiked: false,
    isSold: false,
  },
  {
    id: '4',
    title: '考研英语真题黄皮书全套',
    price: 45,
    originalPrice: 128,
    image: 'https://img.alicdn.com/i1/2214456995702/O1CN0133NUUG1rzZBh6f6l8_!!2214456995702.jpg',
    category: '图书教材',
    condition: 'good' as const,
    description: '2025考研英语一真题，2005-2024年全套，有少量笔记。',
    sellerId: '5',
    sellerName: '刘同学',
    sellerAvatar: '',
    campus: '成龙校区',
    publishTime: '3天前',
    views: 67,
    likes: 12,
    isLiked: false,
    isSold: false,
  },
  {
    id: '5',
    title: '宜家书架 白色',
    price: 80,
    originalPrice: 249,
    image: 'https://img10.360buyimg.com/n1/s720x720_jfs/t1/317800/39/18560/12314/688403c4F87a042c6/ee4b7273671b65db.jpg',
    category: '家具家电',
    condition: 'fair' as const,
    description: '大四毕业出，使用三年，尺寸80x28x202cm，需自提。',
    sellerId: '6',
    sellerName: '陈同学',
    sellerAvatar: '',
    campus: '狮子山校区',
    publishTime: '1周前',
    views: 45,
    likes: 8,
    isLiked: false,
    isSold: false,
  },
  {
    id: '6',
    title: 'AirPods Pro 2 代',
    price: 980,
    originalPrice: 1899,
    image: 'https://img.pconline.com.cn/images/upload/upc/tx/onlinephotolib/2209/08/c0/332671567_1662587953715.jpg',
    category: '数码电子',
    condition: 'like-new' as const,
    description: '2024年购买，使用半年，带MagSafe充电盒，配件齐全。',
    sellerId: '7',
    sellerName: '赵同学',
    sellerAvatar: '',
    campus: '成龙校区',
    publishTime: '6小时前',
    views: 198,
    likes: 36,
    isLiked: false,
    isSold: false,
  },
]

export const mockLostItems = [
  {
    id: 'l1',
    title: '校园卡丢失',
    type: 'lost' as const,
    image: 'https://pic17.997788.com/_pic_search/00/43/94/55/43945507.jpg',
    location: '图书馆三楼阅览室',
    time: '2026-06-29 14:30',
    description: '蓝色校园卡套，姓名：张三，学号：20231001001',
    publisherId: '8',
    publisherName: '张三',
    publisherAvatar: '',
    phone: '138****1234',
    isFound: false,
  },
  {
    id: 'l2',
    title: '黑色钱包',
    type: 'found' as const,
    image: 'https://tse1-mm.cn.bing.net/th/id/OIP-C._b67Edf9C5FCBkjVu48dDQAAAA?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    location: '食堂二楼',
    time: '2026-06-28 12:00',
    description: '黑色皮质钱包，内有身份证和银行卡若干，请失主联系认领。',
    publisherId: '9',
    publisherName: '食堂阿姨',
    publisherAvatar: '',
    phone: '139****5678',
    isFound: true,
  },
  {
    id: 'l3',
    title: '华为Mate40 Pro手机',
    type: 'lost' as const,
    image: 'https://ts3.tc.mm.bing.net/th/id/OIP-C.VYC3uESlZ5-4KXRK4yru2QHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
    location: '教学楼A栋302教室',
    time: '2026-06-29 10:00',
    description: '黑色手机壳，屏幕有保护膜，已关机，请捡到的同学联系我。',
    publisherId: '10',
    publisherName: '李四',
    publisherAvatar: '',
    phone: '137****9012',
    isFound: false,
  },
]

export const mockGroupBuys = [
  {
    id: 'g1',
    title: '瑞幸咖啡拼单',
    image: 'https://gd-hbimg.huaban.com/f0ac5953b11f1da11f1651c69907b664545f65c99539b-TFsXNJ_fw658webp',
    price: 25,
    originalPrice: 38,
    minPeople: 5,
    currentPeople: 3,
    deadline: '2026-06-30 18:00',
    description: '瑞幸新品拼单，满5人享员工价，仅限成龙校区附近同学。',
    organizerId: '11',
    organizerName: '王五',
    organizerAvatar: '',
    campus: '成龙校区',
    status: 'active' as const,
  },
  {
    id: 'g2',
    title: '考研资料团购',
    image: 'https://ts3.tc.mm.bing.net/th/id/OIP-C.PuPb-bC4iXLl5EUPPRCU8gHaEt?rs=1&pid=ImgDetMain&o=7&rm=3',
    price: 89,
    originalPrice: 158,
    minPeople: 10,
    currentPeople: 8,
    deadline: '2026-07-01 23:59',
    description: '2026考研政治+英语全套资料，团购价89元，包邮到家。',
    organizerId: '12',
    organizerName: '赵六',
    organizerAvatar: '',
    campus: '全校',
    status: 'active' as const,
  },
  {
    id: 'g3',
    title: '健身房月卡拼团',
    image: 'https://ts2.tc.mm.bing.net/th/id/OIP-C.o6W8rkBNkmkp_IHiiTioAAHaEi?rs=1&pid=ImgDetMain&o=7&rm=3',
    price: 150,
    originalPrice: 299,
    minPeople: 3,
    currentPeople: 2,
    deadline: '2026-06-29 20:00',
    description: '学校附近健身房月卡，3人成团，每人150元。',
    organizerId: '13',
    organizerName: '孙七',
    organizerAvatar: '',
    campus: '狮子山校区',
    status: 'active' as const,
  },
]

export const mockErrands = [
  {
    id: 'e1',
    title: '帮忙取快递',
    image: 'https://ts1.tc.mm.bing.net/th/id/R-C.1b5e70cf58847fa1affab2614834c7e0?rik=umFKI9AOjGIpmw&riu=http%3a%2f%2fheadscm.com%2fuserimages%2f20220721%2f62d8ba6d4d55f7.17879890.png&ehk=doLyILhi1GnSOzEyeKnaniORI2x3Qthc5MHoGya0wXs%3d&risl=&pid=ImgRaw&r=0',
    reward: 10,
    location: '菜鸟驿站',
    destination: '狮子山校区宿舍',
    description: '有一个大件快递需要从菜鸟驿站搬到狮子山校区宿舍，大约10公斤。',
    requesterId: '14',
    requesterName: '周同学',
    requesterAvatar: '',
    phone: '136****3456',
    time: '尽快',
    status: 'pending' as const,
    takerId: null,
  },
  {
    id: 'e2',
    title: '帮忙占座',
    image: 'https://images.unsplash.com/photo-1544717302-de293b95efc6?w=400&h=400&fit=crop',
    reward: 5,
    location: '图书馆',
    destination: '图书馆',
    description: '明天早上8点帮忙在图书馆三楼占个座，谢谢！',
    requesterId: '15',
    requesterName: '吴同学',
    requesterAvatar: '',
    phone: '135****7890',
    time: '明天08:00',
    status: 'pending' as const,
    takerId: null,
  },
  {
    id: 'e3',
    title: '帮忙打印资料',
    image: 'https://images.unsplash.com/photo-1544717302-de293b95efc6?w=400&h=400&fit=crop',
    reward: 8,
    location: '打印店',
    destination: '教学楼B栋',
    description: '帮忙打印20页PDF资料，送到教学楼B栋501教室。',
    requesterId: '16',
    requesterName: '郑同学',
    requesterAvatar: '',
    phone: '134****2345',
    time: '今天下午',
    status: 'pending' as const,
    takerId: null,
  },
]

export const mockMessages = [
  {
    id: 'm1',
    userId: '2',
    userName: '李同学',
    userAvatar: '',
    lastMessage: '你好，MacBook还在吗？',
    lastTime: '10:30',
    unreadCount: 2,
    messages: [
      { id: 'mm1', senderId: '2', senderName: '李同学', senderAvatar: '', content: '你好，MacBook还在吗？', type: 'text' as const, timestamp: '10:30', isRead: false },
      { id: 'mm2', senderId: '2', senderName: '李同学', senderAvatar: '', content: '我想了解一下具体情况', type: 'text' as const, timestamp: '10:31', isRead: false },
    ],
  },
  {
    id: 'm2',
    userId: '3',
    userName: '王同学',
    userAvatar: '',
    lastMessage: '[图片]',
    lastTime: '昨天',
    unreadCount: 0,
    messages: [
      { id: 'mm3', senderId: '3', senderName: '王同学', senderAvatar: '', content: 'iPhone价格可以商量吗？', type: 'text' as const, timestamp: '昨天 18:20', isRead: true },
      { id: 'mm4', senderId: 'me', senderName: '我', senderAvatar: '', content: '最低4000元，不能再少了', type: 'text' as const, timestamp: '昨天 18:25', isRead: true },
      { id: 'mm5', senderId: '3', senderName: '王同学', senderAvatar: '', content: '[图片]', image: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=300&h=300&fit=crop', type: 'image' as const, timestamp: '昨天 18:30', isRead: true },
    ],
  },
  {
    id: 'm3',
    userId: 'system',
    userName: '系统通知',
    userAvatar: '',
    lastMessage: '您的发布已通过审核',
    lastTime: '2天前',
    unreadCount: 1,
    messages: [
      { id: 'mm6', senderId: 'system', senderName: '系统通知', senderAvatar: '', content: '您的发布"Apple MacBook Air M2"已通过审核', type: 'text' as const, timestamp: '2天前', isRead: false },
    ],
  },
]

export const categories = [
  { id: 'all', name: '全部', icon: '🏠' },
  { id: 'digital', name: '数码电子', icon: '📱' },
  { id: 'sports', name: '运动户外', icon: '⚽' },
  { id: 'books', name: '图书教材', icon: '📚' },
  { id: 'furniture', name: '家具家电', icon: '🪑' },
  { id: 'clothing', name: '服饰鞋包', icon: '👔' },
  { id: 'other', name: '其他', icon: '🎁' },
]
